import { DEFAULT_BKT, type BktParams } from '../tutor/bkt';

// Lesson content handling (Learn mode, PRD F8). Pure functions only — no DB, no
// I/O — so the rules that matter (what the browser is allowed to see, what
// counts as a right answer) are unit-tested.

// The marker for the blank in a "Try it" step.
export const BLANK = '____';

// BKT parameters for a multiple-choice lesson answer, as opposed to solving a
// level. Guessing is far easier here (four options, and weak ones can be
// eliminated) → high guess rate. The questions are deliberate traps, so even a
// student who knows the topic slips more often → higher slip rate. And
// answering a question is not practice → NO learning credit. Mastery is earned
// in the levels.
export const LESSON_BKT: BktParams = { ...DEFAULT_BKT, pS: 0.2, pG: 0.4, pT: 0 };

// Is this step one the student answers?
export function isQuestion(step: LessonStep): boolean {
  return step.type === 'predict' || step.type === 'concept';
}

// Does this question count as evidence of what the student knows? Only if it
// comes AFTER the teaching (an "explain" step). In PRIMM the first prediction is
// made before anything has been taught — it's there to make the student think,
// and being wrong is expected, so it must not lower their mastery estimate.
export function countsAsEvidence(steps: LessonStep[], stepId: string): boolean {
  const at = steps.findIndex((s) => s.id === stepId);
  const taught = steps.findIndex((s) => s.type === 'explain');
  return at >= 0 && taught >= 0 && taught < at;
}

// ---- Authored code -> what the student sees ---------------------------------

// A line of lesson code may end in `//~ narration`, which is Nova's line for
// that line in the Watch-it-run step. It is stripped before the code is shown
// or compiled. Mirrors splitNarration() in content/build-lessons.mjs.
export function splitNarration(code: string): { code: string; notes: Record<number, string> } {
  const notes: Record<number, string> = {};
  const clean = code
    .split('\n')
    .map((line, i) => {
      const at = line.indexOf('//~');
      if (at < 0) return line;
      notes[i + 1] = line.slice(at + 3).trim();
      return line.slice(0, at).trimEnd();
    })
    .join('\n');
  return { code: clean, notes };
}

// ---- Fill-in answers ---------------------------------------------------------

// Compare typed Java loosely enough to be fair, strictly enough to be right:
// whitespace is irrelevant in Java, and a trailing semicolon is usually already
// in the surrounding code. Everything else must match.
export function normalizeFillAnswer(answer: string): string {
  return answer.replace(/\s+/g, '').replace(/;+$/, '');
}

// Is this one of the answers the content author listed (and the build script
// proved correct)? Anything else still gets run for real before being rejected.
export function isAcceptedFill(answer: string, accepted: string[]): boolean {
  const a = normalizeFillAnswer(answer);
  return accepted.some((x) => normalizeFillAnswer(x) === a);
}

// Put the student's answer into the blank, giving a complete program to run.
export function fillProgram(code: string, answer: string): string {
  return splitNarration(code).code.replace(BLANK, answer);
}

// ---- The shape of a lesson ---------------------------------------------------

export interface PredictOption {
  text: string; // what the program might print
  why: string; // the explanation for choosing it (right or wrong)
}

// A question the student answers: a Predict step (what does this print?) or a
// Concept step (theory, taken from content/questions/java-oop.json).
export const QUESTION_TYPES = ['predict', 'concept'] as const;

// One array drawn beside the trace (searching, sorting). Every name in here is
// checked against the recording by the build script, so the picture can never
// disagree with what the JVM actually did.
export interface TraceVisual {
  array: string;
  pointers?: string[];
  range?: [string, string];
  mode?: 'cells' | 'bars';
}

export interface LessonStep {
  id: string;
  type: 'hook' | 'predict' | 'trace' | 'explain' | 'fill' | 'concept';
  // hook / explain
  title?: string;
  body?: string;
  points?: string[];
  pattern?: string;
  // predict / concept
  prompt?: string;
  code?: string;
  options?: PredictOption[] | string[]; // {text, why} for predict, plain text for concept
  answer?: number; // generated by the build script — never sent to the browser
  // concept (filled from the question bank by content/build-lessons.mjs)
  ref?: string;
  question?: string;
  topic?: string;
  explanation?: string; // the bank's explanation, shown after answering
  // trace
  from?: string; // the step whose code this traces
  trace?: unknown; // recorded by content/tools/Tracer.java
  visual?: TraceVisual; // optional array picture, checked by content/build-lessons.mjs
  // added by sanitizeLesson for predict and trace steps: line number -> Nova's
  // narration, split out of the code (the browser needs both halves)
  notes?: Record<number, string>;
  // fill
  accepted?: string[]; // never sent to the browser
  wrong?: string[];
  expectedOutput?: string;
  hint?: string;
  explain?: string; // revealed once they get it right
}

export interface LessonContent {
  steps: LessonStep[];
}

// What the browser receives: the same steps with every answer removed, and the
// narration split out of the code. Options keep their text (they have to be
// shown) but lose `why`, which would give the answer away — the server returns
// the right `why` after the student chooses, exactly like hidden test cases.
export function sanitizeLesson(content: LessonContent): LessonStep[] {
  const steps = content.steps ?? [];
  return steps.map((s) => {
    if (s.type === 'predict') {
      const { code, notes } = splitNarration(s.code ?? '');
      const options = (s.options ?? []) as PredictOption[];
      return { id: s.id, type: s.type, prompt: s.prompt, code, notes, options: options.map((o) => ({ text: o.text })) };
    }
    if (s.type === 'trace') {
      const source = s.from ? steps.find((x) => x.id === s.from) : s;
      const { code, notes } = splitNarration(source?.code ?? '');
      return { id: s.id, type: s.type, title: s.title, code, notes, trace: s.trace, visual: s.visual };
    }
    if (s.type === 'concept') {
      // Theory question: the text and the options, never the answer.
      return { id: s.id, type: s.type, question: s.question, topic: s.topic, options: (s.options ?? []) as string[] };
    }
    if (s.type === 'fill') {
      const { code } = splitNarration(s.code ?? '');
      return {
        id: s.id,
        type: s.type,
        prompt: s.prompt,
        code,
        expectedOutput: s.expectedOutput,
        hint: s.hint,
        blank: BLANK,
      };
    }
    return s; // hook and explain carry no answers
  }) as LessonStep[];
}

// How many of the lesson's questions (predict + concept) the student got right
// on their first try.
export function scoreAnswers(answered: Record<string, boolean>, steps: LessonStep[]): { correct: number; total: number } {
  const questions = steps.filter((s) => s.type === 'predict' || s.type === 'concept').map((s) => s.id);
  const first = questions.filter((id) => id in answered);
  return { correct: first.filter((id) => answered[id]).length, total: questions.length };
}
